### ISSUE TITLE
Don't use AppIndicator

### ISSUE THREAD

**Issue by teohhanhui** [vinifmor/fpakman#32]
In Gnome Shell, a panel menu would be much preferable, e.g. https://gitlab.manjaro.org/applications/pamac/blob/master/data/gnome-shell/pamac-updates@manjaro.org/extension.js

**Comment by vinifmor** [comment]
Hi, thank you for your feedback. Let me ask you: launching the app with the command **fpakman --tray==0** helps ? The next main **AUR** release will include two desktop entries: the default one launching only the panel, and the second launching the tray icon. It will look something like:
![image](https://user-images.githubusercontent.com/4312414/62427969-aee25780-b6d1-11e9-84b1-31bb180f3cd8.png)

**Comment by teohhanhui** [comment]
Sorry, I think we had some miscommunication. I was talking about a Gnome Shell extension. I don't see that option in the latest version of `bauh`. I think it's important if `bauh` is to be the default GUI package manager for `snap` and `flatpak` in Manjaro, considering that Gnome is an officially supported edition, and that we have the [pamac-updates](https://gitlab.manjaro.org/applications/pamac/blob/master/data/gnome-shell/pamac-updates@manjaro.org/extension.js) Gnome Shell extension.

**Comment by vinifmor** [comment]
Alright. I will have a look in how it can be accomplished and put in the **bauh** roadmap.
