### ISSUE TITLE
Support for appimages

### ISSUE THREAD

**Issue by tiotrom** [vinifmor/fpakman#33]
Your roadmap says you want to support other packaging technologies. Is appimage one of them? And if so how far on this roadmap it is? Thanks for doing this! :)

**Comment by vinifmor** [comment]
Hi... **AppImage** is my first option as a new extension for **fpakman**. Unfortunately, **AppImageHub** API does not provide enough information to make this integration happen now. But I am looking for other ways to make this possible.

**Comment by tiotrom** [comment]
Awesome!
