### ISSUE TITLE
Add switch to launch in tray or window

### ISSUE THREAD

**Issue by oberon-manjaro** [vinifmor/fpakman#34]
First of all let me say thank you for this little gem piece of software, KUDOS!!
When someone first launches **fpakman** you can assume that they are about to actively use it. So I think it would make more sense to launch it in its own window right away instead of dropping to the tray.
I assume your intention is to have it autostarted, where of course tray launch will be desirable.
So I guess introducing a switch would make sense here?

**Comment by vinifmor** [comment]
Hi, @oberon-manjaro. This behavior is possible in **0.5.0**. I have just released it. Have a look at:
https://forum.manjaro.org/t/fpakman-a-gui-for-flatpak-and-snap-management/96180/62

In the **AUR** release, it will now create two desktop entries for the user. The default opens only the panel, and second adds the icon to the tray.  I'm happy to know that the app is useful for you. Thank you for the feedback.

**Comment by oberon-manjaro** [comment]
That sounds great! Thank you very much. Will test tonight.

**Comment by oberon-manjaro** [comment]
After trying this in i3 I have another request.
Would it be possible for you to make ``--tray=0`` the default instead of 1?
The problem in i3 is that **dmenu** scans **/usr/bin** rather than launchers and for that reason just offers 'fpakman' when you search for it. So as a result again it launches fpakman in the tray :wink:

**Comment by vinifmor** [comment]
Yes, it's possible... it seems the panel is the default choice for most users. I will include this change in **0.5.1**.

**Comment by oberon-manjaro** [comment]
Thanks a lot! :smile:

**Comment by vinifmor** [comment]
I've just published **0.5.1.RC-4** to **fpakman-staging** (AUR) with this change. Could you please give me a feedback if it is working ? I've also added a custom command to call the tray **fpakman-tray** via terminal.

**Comment by oberon-manjaro** [comment]
Working as expected. Thank you very much!

**Comment by vinifmor** [comment]
Added in **0.5.1**
