### ISSUE TITLE
Uninstallation doesn't remove .desktop shortcut in ~/.local/share/applications

### ISSUE THREAD

**Issue by erenseymen** [vinifmor/fpakman#4]
Installed via AUR.
OS: Manjaro Xfce

**Comment by vinifmor** [comment]
It seems that the current way AUR works is not possible to define a custom cleanup operation. But I will try to figure something out. If somebody already knows how, please, write here.

**Comment by vinifmor** [comment]
Fixed the behavior for the **staging** branch. It will be available in the next main **AUR** release as well.
